### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by zwq1111** [zhiyuns/AFCM#1]
Thanks for the code you provided. But I meet some problems when I run the code, I want to know whether the code is entire or not. If it is entire, I am so sorry to bother you. If it is not,  I would like you to post the complete code. Thank you very much again!

**Comment by zhiyuns** [comment]
Sorry for the late response. We are sorry for the potential problems with the SR experiments and update the code to fix them. Please feel free to contact us if you have further questions.

**Comment by zhiyuns** [comment]
We are sorry for the potential problems with the SR experiments and update the code to fix them. Please feel free to contact us if you have further questions.

**Comment by zwq1111** [comment]
Thank you very much for your reply! I have another question, I noticed that you have processed the dataset used accordingly when running the code. I am currently looking into this part and I was wondering if it would be possible to tell me how the dataset was processed.

**Comment by zhiyuns** [comment]
As described by the paper, when performing cross-modality synthesis, we first co-registrate the modalities using ANTsPy (<rigid registration> mode) and then prepare the h5 file using ./data/prepare_h5.py. If you want to perform super-resolution, please resample the HR image to get LR image, and upsample the LR image using <nearest intepolation> to match the shape with HR image. After that, prepare the h5 file using ./data/prepare_h5.py. We also upload an example as ./data/ixi_demo.h5 for a clearer demonstration of this process.

**Comment by zwq1111** [comment]
Thanks again for your reply! I have one more question about the code. I have downloaded the required ixi dataset on the website, but I didn't find the 'T1_HR' and 'T2_FLAIR_linear' modality data in ./data/prepare_h5.py. 
![code](https://github.com/zhiyuns/AFCM/assets/149295887/67fc3143-4bee-401b-816c-e904b0028927)

**Comment by zwq1111** [comment]
Thanks again for your reply! I have one more question about the code. I have downloaded the required ixi dataset on the website, but I didn't find the 'T1_HR' and 'T2_FLAIR_linear' modality data in ./data/prepare_h5.py. I'd like to ask you for details about it.
![Uploading code.jpg…]()

**Comment by zwq1111** [comment]
Thanks again for your reply! I have one more question about the code. I have downloaded the required ixi dataset on the website, but I didn't find the 'T1_HR' and 'T2_FLAIR_linear' modality data in ./data/prepare_h5.py. I'd like to ask you for details about it.
![code](https://github.com/zhiyuns/AFCM/assets/149295887/480abb03-3259-4f59-aa23-83aff4daa16c)

**Comment by zhiyuns** [comment]
It's just an example, you can modify it to fit the actual task and situation. For IXI, you can modify it with ['T1', 'T2', 'PD'] to reproduce our result.
