### ISSUE TITLE
Missing attribute in models

### ISSUE THREAD

**Issue by ZishengHuang** [zhiyuns/AFCM#2]
Congrats and thanks for codes.

### Issue Description:
I am following the super resolution setting provided.
```
python train.py --config-file ./configs/adni/stylegan3/sr_5.yml --model stylegan3
```
Initially, I got the errors below and fixed them by declare their bool values in _**models.comodgan_model.py**_
```
AttributeError: 'StyleGAN3Model' object has no attribute 'extra_b' and 'sg'
```
Now I have:
```
AttributeError: 'StyleGAN3Model' object has no attribute 'netSG'
```

In my aspect, the '**netSG**' may should be defined in _models.pix2pix_model.py_, as the same as **'netD**' and '**netG**':
```
self.netG = define_G(**opt.model.G, gpu_ids=self.gpu_ids)
if self.isTrain:  
       self.netD = define_D(**opt.model.D, gpu_ids=self.gpu_ids)
```

Could you provide further material to address this problem...?
Thanks you again and wish you have a good day.

**Comment by Astrostellar** [comment]
Thank you for following our work! We notice that the python file **models.comodgan_model.py** might have some problems, as our previous version used a segmentation model to guide the generation process. Now we have updated the code and fixed the problems. Please feel free to contact us if you have further questions.

**Comment by ZishengHuang** [comment]
Glad to have your useful response and thanks for your patience!!
