### ISSUE TITLE
How to simulate low resolution MRI

### ISSUE THREAD

**Issue by pyzheng01** [zhiyuns/AFCM#3]
Thank you very much for your work, could you please explain in detail how to simulate low resolution MRI?

**Comment by zhiyuns** [comment]
Sorry for the late response, as we are preparing for the journal version of this repository. We use the Gaussian filter (implemented by a 1D convolution with predefined blurring kernel) to smooth the HR image followed by downsampling. The FWHM of Gaussian filter is calculated based on the downsampling factor. For the construction of blurring kernel and determination of FWHM, please refer to [smore](https://gitlab.com/iacl/smore/-/tree/main?ref_type=heads) for more details.
