### ISSUE TITLE
May I ask about the issue of modifying multimodal sequence code

### ISSUE THREAD

**Issue by 1416261278** [zhiyuns/AFCM#4]
Hello, I am a student who has just started learning PyTorch. I noticed in your article that it supports multimodal sequence input. How can I implement multimodal sequence input? Currently, I am inputting multiple modalities, and it seems that there are many network structures that need to be modified. Is there any good way to solve this problem?

**Comment by 1416261278** [comment]
If I didn't see your message in time, could you please send me an email? My email is vipyw99@163.com I am looking forward to your reply very much. Your reply will be of great help to me

**Comment by zhiyuns** [comment]
Our conference version does not contain the experiments with multimodal inputs. However, we have implemented this in our repository, by simply concatenating the inputs to the channel dimension. If you want to do this, you need to made some modification to the config files. Firstly, you need to modify the dataloader configs. 'loaders.cat_inputs' should be set to True, and 'loaders.raw_internal_path_in' should be set to the values you need (for example, ['T1', 'T2']). Secondly, you need to modify the model configs. 'model.G.img_channels_in' should be set to 4*(num_of_input_modalities) and 'model.D.img_channels' should be set to 4*(num_of_input_modalities)+1. Then it should be working. If you have any further questions, don't hesitate to contact us.

**Comment by 1416261278** [comment]
Dear Zhiyuns, thank you for providing the modification ideas! The problem that my code has solved so far, 
best wishes



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年9月12日(星期四) 晚上10:48
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [zhiyuns/AFCM] May I ask about the issue of modifying multimodal sequence code (Issue #4)














 
Our conference version does not contain the experiments with multimodal inputs. However, we have implemented this in our repository, by simply concatenating the inputs to the channel dimension. If you want to do this, you need to made some modification to the config files. Firstly, you need to modify the dataloader configs. 'loaders.cat_inputs' should be set to True, and 'loaders.raw_internal_path_in' should be set to the values you need (for example, ['T1', 'T2']). Secondly, you need to modify the model configs. 'model.G.img_channels_in' should be set to 4*(num_of_input_modalities) and 'model.D.img_channels' should be set to 4*(num_of_input_modalities)+1. Then it should be working. If you have any further questions, don't hesitate to contact us.
