### ISSUE TITLE
Consultation about SG code

### ISSUE THREAD

**Issue by 1416261278** [zhiyuns/AFCM#5]
Hello, I would like to ask if there is a self. sg in the pix2pix part of COMODGAN's code that seems to have not been found? Has the released version not been released yet?

**Comment by zhiyuns** [comment]
We tried to add the segmentation model to guide the generation process (as denoted by self.sg), but we discarded this as it was not included in our conference paper. If you are interested in segmentation-guided procedure, please refer to our journal version [UniCOAL](https://github.com/zhiyuns/UniCOAL).
