### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by MaoFuyou** [zhiyuns/AFCM#6]
您好，为了方便学习，可否方便分享您在论文中使用的处理后的数据

**Comment by zhiyuns** [comment]
I am afraid that we do not have the permission to share the data. If you want to reproduce the results on IXI or ADNI datasets, you can download them from [IXI](https://brain-development.org/ixi-dataset/) or [ADNI](https://adni.loni.usc.edu/), then process them with our codes in `./data/prepare_h5.py`. An example is also provided in `./data/ixi_demo.h5`. I am sorry about the convenience, and please do not hesitate to contact us if you have further questions.

**Comment by MaoFuyou** [comment]
Yes，Thank you for your explaination；If chances， could I get your wechat number to communicate deeply. Thank you.
